export const localizations: any = {
  fi: {
    manageMaintenancesButtonTooltip: 'Hallitse huoltoja',
    upcomingMaintenances: 'Tulevat huollot',
    type: 'Tyyppi',
    description: 'Kuvaus',
    createdBy: 'Luonut',
    startTime: 'Alkamisaika',
    endTime: 'Päättymisaika',
    duration: 'Kesto',
    repeatEnds: 'Toisto päättyy',
    createNewMaintenance: 'Luo uusi huolto',
    ok: 'OK',
    close: 'Sulje',
    cancel: 'Peruuta',
    oneTime: 'Yksittäinen',
    daily: 'Päivittäinen',
    weekly: 'Viikottainen',
    monthly: 'Kuukausittainen',
    oneTimeAbbr: 'Yksittäinen',
    dailyAbbr: 'Päivittäinen',
    weeklyAbbr: 'Viikottainen',
    monthlyAbbr: 'Kuukausittainen',
    first: 'Ensimmäinen',
    second: 'Toinen',
    third: 'Kolmas',
    fourth: 'Neljäs',
    last: 'Viimeinen',
    weekday0: 'Maanantai',
    weekday1: 'Tiistai',
    weekday2: 'Keskiviikko',
    weekday3: 'Torstai',
    weekday4: 'Perjantai',
    weekday5: 'Lauantai',
    weekday6: 'Sunnuntai',
    month0: 'Tammikuu',
    month1: 'Helmikuu',
    month2: 'Maaliskuu',
    month3: 'Huhtikuu',
    month4: 'Toukokuu',
    month5: 'Kesäkuu',
    month6: 'Heinäkuu',
    month7: 'Elokuu',
    month8: 'Syyskuu',
    month9: 'Lokakuu',
    month10: 'Marraskuu',
    month11: 'Joulukuu',
    atLeastOneHostMustBeSelected: 'Ainakin yhden kohteen täytyy olla valittu',
    maintenanceDescriptionIs: 'Huollon kuvaus on',
    charsTooLong: 'merkkiä liian pitkä',
    dayFieldMustContainInteger: 'Kentän "Toistetaan n päivän välein" täytyy sisältää kokonaisluku.',
    weekFieldMustContainInteger: 'Kentän "Toistetaan n viikon välein" täytyy sisältää kokonaisluku.',
    oneWeekdayMustBeChosen: 'Ainakin yhden viikonpäivän täytyy olla valittu.',
    oneMonthMustBeChosen: 'Ainakin yhden kuukauden täytyy olla valittu.',
    monthFieldMustContainInteger: 'Kentän "Toistetaan kuukauden päivänä" täytyy sisältää kokonaisluku.',
    repeatMustEndAfterStartTime: 'Toiston päättymisaika pitää olla huollon alkamisajan jälkeen.',
    repeatEndDateCantBeInPast: 'Toiston loppumisaika ei voi olla menneisyydessä.',
    maintenanceEndMustBeAfterStart: 'Huollon päättymisajan pitää olla huollon alkamisajan jälkeen.',
    maintenanceEndCantBeInPast: 'Huollon päättymisaika ei voi olla menneisyydessä.',
    maintenanceType: 'Huollon tyyppi',
    repeatEveryNDays: 'Toistetaan [n] päivän välein',
    repeatEveryNWeeks: 'Toistetaan [n] viikon välein',
    repeatOnWeekday: 'Toistetaan viikonpäivänä',
    repeatOnMonth: 'Toistetaan kuukautena',
    selectAll: 'Valitse kaikki',
    repeatOn: 'Toistetaan',
    nthDayOfMonth: 'Kuukauden [n] päivänä',
    nthWeekdayOfMonth: 'Kuukauden [n] viikonpäivänä',
    repeatOnDayOfMonth: 'Toistetaan kuukauden päivänä',
    repeatOnDayOfWeek: 'Toistetaan viikonpäivänä',
    secondTuesdayOfApril: '(esim. kuukauden toinen tiistai)',
    day: 'Päivä',
    month: 'Kuukausi',
    year: 'Vuosi',
    hour: 'Tunti',
    minute: 'Minuutti',
    endRepeat: 'Lopeta toisto',
    startRepeat: 'Aloita toisto',
    maintenanceDuration: 'Huollon kesto',
    setPreciseEndTime: 'Määritä tarkka päättymisaika',
    maintenanceListStartTime: 'Aloitusaika',
    maintenanceListEndTime: 'Lopetusaika',
    maintenanceFormStartTime: 'Aloita huolto',
    maintenanceFormEndTime: 'Lopeta huolto',
    back: 'Takaisin',
    next: 'Eteenpäin',
    maintenanceDescription: 'Huollon kuvaus',
    selectHosts: 'Valitse huollon kohteet',
    allHosts: 'Kaikki',
    saveChanges: 'Tallenna muutokset',
    createMaintenance: 'Luo huolto',
    hosts: 'Kohteet',
    repeatStarts: 'Toisto alkaa',
    cancelMaintenanceConfirmTitle: 'Huollon keskeyttäminen',
    areYouSureWantToCancelMaintenance: 'Haluatko varmasti keskeyttää huollon?',
    cancelMaintenanceConfirmButtonText: 'Keskeytä huolto',
    deleteMaintenanceConfirmTitle: 'Huollon poistaminen',
    areYouSureWantToDeleteMaintenance: 'Haluatko varmasti poistaa huollon?',
    deleteMaintenanceConfirmButtonText: 'Poista huolto',
    cantCancelStartedPeriodicMaintenance: 'Käynnissä olevaa ajastettua huoltoa ei voi keskeyttää.',
    selectedActionWillDeleteAllMaintenancesInSeries:
      'Valitsemasi toiminto poistaa kaikki samaan sarjaan kuuluvat huollot.',
    areYouSureWantToContinue: 'Haluatko varmasti jatkaa?',
    areYouSureWantToDeletePeriodicMaintenance: 'Haluatko varmasti poistaa ajastetun huollon?',
    allMaintenancesInSeriesWillBeDeleted: 'Kaikki samaan sarjaan kuuluvat tulevat huollot poistetaan.',
    maintenanceHasBeenDeleted: 'Huolto on poistettu onnistuneesti.',
    maintenancehasBeenCanceled: 'Huolto on keskeytetty.',
    systemStatusWillBeUpdated: 'Järjestelmän tila päivittyy 1-2 minuutissa.',
    newMaintenanceHasBeenStarted: 'Uusi huolto on käynnistetty onnistuneesti.',
    maintenanceHasBeenUpdated: 'Huolto on päivitetty onnistuneesti.',
    newMaintenanceHasBeenCreated: 'Uusi huolto luotu onnistuneesti.',
    modifyMaintenance: 'Muokkaa huoltoa',
    searchWithName: 'Hae nimellä',
    startTimeBeforeError: 'Huolto ei voi alkaa ennen $$ UTC-aikarajoitusten vuoksi.',
    startTimeAfterError: 'Huolto ei voi alkaa $$ jälkeen UTC-aikarajoitusten vuoksi.',
    startTimeFixDaily: 'Muuta huollon alkamisaikaa tai konfiguroi huolto toistumaan joka päivä.',
    startTimeFixWeekly: 'Muuta huollon alkamisaikaa tai konfiguroi huolto toistumaan joka viikko.',
    startTimeFixMonthlyNthWeekday: 'Muuta huollon alkamisaikaa.',
    startTimeFixMonthlyNthDayOfMonth: 'Muuta huollon alkamisaikaa tai kuukauden päivää.',
    cannotShowDatesTimeZoneIssue: 'Huollon aikoja ei voida näyttää nykyisellä aikavyöhykkeellä',
  },
  en: {
    manageMaintenancesButtonTooltip: 'Manage maintenances',
    upcomingMaintenances: 'Upcoming Maintenances',
    type: 'Type',
    description: 'Description',
    createdBy: 'Created by',
    startTime: 'Start time',
    endTime: 'End time',
    duration: 'Duration',
    repeatEnds: 'Repeat ends',
    createNewMaintenance: 'Create new maintenance',
    ok: 'OK',
    close: 'Close',
    cancel: 'Cancel',
    oneTime: 'One time',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    oneTimeAbbr: 'One-time',
    dailyAbbr: 'Daily',
    weeklyAbbr: 'Weekly',
    monthlyAbbr: 'Monthly',
    first: 'First',
    second: 'Second',
    third: 'Third',
    fourth: 'Fourth',
    last: 'Last',
    weekday0: 'Monday',
    weekday1: 'Tuesday',
    weekday2: 'Wednesday',
    weekday3: 'Thursday',
    weekday4: 'Friday',
    weekday5: 'Saturday',
    weekday6: 'Sunday',
    month0: 'January',
    month1: 'February',
    month2: 'March',
    month3: 'April',
    month4: 'May',
    month5: 'June',
    month6: 'July',
    month7: 'August',
    month8: 'September',
    month9: 'October',
    month10: 'November',
    month11: 'December',
    atLeastOneHostMustBeSelected: 'At least one target must be selected',
    maintenanceDescriptionIs: 'Maintenance description is',
    charsTooLong: 'characters too long',
    dayFieldMustContainInteger: 'Field "Repeat every n days" must contain an integer.',
    weekFieldMustContainInteger: 'Field "Repeat every n weeks" must contain an integer.',
    oneWeekdayMustBeChosen: 'At least one weekday must be chosen.',
    oneMonthMustBeChosen: 'At least one month must be chosen.',
    monthFieldMustContainInteger: 'Field "Repeat day of month" must contain an integer.',
    repeatMustEndAfterStartTime: 'Repeat must after maintenance start time.',
    repeatEndDateCantBeInPast: "Repeat end date can't be in the past.",
    maintenanceEndMustBeAfterStart: 'Maintenance end time must be after start time.',
    maintenanceEndCantBeInPast: "Maintenance end time can't be in the past.",
    maintenanceType: 'Maintenance type',
    repeatEveryNDays: 'Repeat every [n] days',
    repeatEveryNWeeks: 'Repeat every [n] weeks',
    repeatOnWeekday: 'Repeat on weekday',
    repeatOnMonth: 'Repeat on month',
    selectAll: 'Select all',
    repeatOn: 'Repeat on',
    nthDayOfMonth: 'Nth day of month',
    nthWeekdayOfMonth: 'Nth weekday of month',
    repeatOnDayOfMonth: 'Repeat on day of month',
    repeatOnDayOfWeek: 'Repeat on day of week',
    secondTuesdayOfApril: '(e.g. 2nd Tuesday of April)',
    day: 'Day',
    month: 'Month',
    year: 'Year',
    hour: 'Hour',
    minute: 'Minute',
    endRepeat: 'End repeat',
    startRepeat: 'Start repeat',
    maintenanceDuration: 'Maintenance duration',
    setPreciseEndTime: 'Set precise end time',
    maintenanceListStartTime: 'Start time',
    maintenanceListEndTime: 'End time',
    maintenanceFormStartTime: 'Start maintenance at',
    maintenanceFormEndTime: 'End maintenance at',
    back: 'Back',
    next: 'Next',
    maintenanceDescription: 'Maintenance description',
    selectHosts: 'Select maintenance targets',
    allHosts: 'All',
    saveChanges: 'Save changes',
    createMaintenance: 'Create maintenance',
    hosts: 'Targets',
    repeatStarts: 'Repeat starts',
    cancelMaintenanceConfirmTitle: 'Maintenance cancelling',
    areYouSureWantToCancelMaintenance: 'Are you sure you want to cancel maintenance?',
    cancelMaintenanceConfirmButtonText: 'Cancel maintenance',
    deleteMaintenanceConfirmTitle: 'Maintenance deletion',
    areYouSureWantToDeleteMaintenance: 'Are you sure you want to delete maintenance?',
    deleteMaintenanceConfirmButtonText: 'Delete maintenance',
    cantCancelStartedPeriodicMaintenance: "You can't cancel a periodic maintenance which has been started.",
    selectedActionWillDeleteAllMaintenancesInSeries:
      'The selected action will delete all maintenances in the same series.',
    areYouSureWantToContinue: 'Are you sure you want to continue?',
    areYouSureWantToDeletePeriodicMaintenance: 'Are you sure you want to delete a periodic maintenance?',
    allMaintenancesInSeriesWillBeDeleted: 'All maintenances in the same series will be deleted.',
    maintenanceHasBeenDeleted: 'Maintenance has been succesfully deleted.',
    maintenancehasBeenCanceled: 'Maintenance has been canceled.',
    systemStatusWillBeUpdated: 'The system status will be updated in 1-2 minutes.',
    newMaintenanceHasBeenStarted: 'New maintenance has been started succesfully.',
    maintenanceHasBeenUpdated: 'Maintenance has been updated succesfully.',
    newMaintenanceHasBeenCreated: 'New maintenance has been created succesfully.',
    modifyMaintenance: 'Modify maintenance',
    searchWithName: 'Search with name',
    startTimeBeforeError: 'Maintenance cannot start before $$ because of UTC timezone constraints.',
    startTimeAfterError: 'Maintenance cannot start after $$ because of UTC timezone constraints.',
    startTimeFixDaily: 'Please change the start time or configure the maintenance to repeat every day.',
    startTimeFixWeekly: 'Please change the start time or configure the maintenance to repeat every week.',
    startTimeFixMonthlyNthWeekday: 'Please change the start time.',
    startTimeFixMonthlyNthDayOfMonth: 'Please change the start time or the day of month.',
    cannotShowDatesTimeZoneIssue: 'Dates cannot be shown in the current timezone',
  },
};
