export const localizations: any = {
  fi: {
    upcomingMaintenances: 'Tulevat huollot',
    type: 'Tyyppi',
    description: 'Kuvaus',
    createdBy: 'Luonut',
    startTime: 'Alkamisaika',
    endTime: 'Päättymisaika',
    duration: 'Kesto',
    repeatEnds: 'Toisto päättyy',
    createNewMaintenance: 'Luo uusi huolto',
    ok: 'OK',
    cancel: 'Peruuta',
    oneTime: 'Yksittäinen',
    daily: 'Päivittäinen',
    weekly: 'Viikottainen',
    monthly: 'Kuukausittainen',
    oneTimeAbbr: 'yksi',
    dailyAbbr: 'pvä',
    weeklyAbbr: 'vko',
    monthlyAbbr: 'kk',
    first: 'Ensimmäinen',
    second: 'Toinen',
    third: 'Kolmas',
    fourth: 'Neljäs',
    last: 'Viimeinen',
    monday: 'Maanantai',
    tuesday: 'Tiistai',
    wednesday: 'Keskiviikko',
    thursday: 'Torstai',
    friday: 'Perjantai',
    saturday: 'Lauantai',
    sunday: 'Sunnuntai',
    january: 'Tammikuu',
    february: 'Helmikuu',
    march: 'Maaliskuu',
    april: 'Huhtikuu',
    may: 'Toukokuu',
    june: 'Kesäkuu',
    july: 'Heinäkuu',
    august: 'Elokuu',
    september: 'Syyskuu',
    october: 'Lokakuu',
    november: 'Marraskuu',
    december: 'Joulukuu',
    atLeastOneHostMustBeSelected: 'Ainakin yhden palvelimen täytyy olla valittu',
    maintenanceDescriptionIs: 'Huollon kuvaus on',
    charsTooLong: 'merkkiä liian pitkä',
    dayFieldMustContainInteger: 'Kentän "Toistetaan n päivän välein" täytyy sisältää kokonaisluku.',
    weekFieldMustContainInteger: 'Kentän "Toistetaan n viikon välein" täytyy sisältää kokonaisluku.',
    oneWeekdayMustBeChosen: 'Ainakin yhden viikonpäivän täytyy olla valittu.',
    oneMonthMustBeChosen: 'Ainakin yhden kuukauden täytyy olla valittu.',
    monthFieldMustContainInteger: 'Kentän "Toistetaan kuukauden päivänä" täytyy sisältää kokonaisluku.',
    repeatMustEndAfterStartTime: 'Toiston päättymisaika pitää olla huollon alkamisajan jälkeen.',
    repeatEndTimeCantBeInPast: 'Toiston päättymisaika ei voi olla menneisyydessä.',
    repeatEndTimeCantOverlapDaylight: 'Toiston päättymisaika ei voi ylittää kesä/talviaika vaihdosta.',
    maintenanceEndMustBeAfterStart: 'Huollon päättymisajan pitää olla huollon alkamisajan jälkeen.',
    maintenanceEndCantBeInPast: 'Huollon päättymisaika ei voi olla menneisyydessä.',
    maintenanceType: 'Huollon tyyppi',
    repeatEveryNDays: 'Toistetaan [n] päivän välein',
    repeatEveryNWeeks: 'Toistetaan [n] viikon välein',
    repeatOnWeekday: 'Toistetaan viikonpäivänä',
    repeatOnMonth: 'Toistetaan kuukautena',
    selectAll: 'Valitse kaikki',
    repeatOn: 'Toistetaan',
    nthDayOfMonth: 'Kuukauden päivänä n',
    nthDayOfWeek: 'Viikonpäivänä n',
    repeatOnDayOfMonth: 'Toistetaan kuukauden päivänä',
    repeatOnDayOfWeek: 'Toistetaan viikonpäivänä',
    secondTuesdayOfApril: '(esim. kuukauden toinen tiistai)',
    day: 'Päivä',
    month: 'Kuukausi',
    year: 'Vuosi',
    hour: 'Tunti',
    minute: 'Minuutti',
    endRepeat: 'Lopeta toisto',
    maintenanceDuration: 'Huollon kesto',
    setPreciseEndTime: 'Määritä tarkka päättymisaika',
    maintenanceEndTime: 'Huollon päättymisaika',
    back: 'Takaisin',
    next: 'Eteenpäin',
    maintenanceDescription: 'Huollon kuvaus',
    selectHosts: 'Palvelimien valinta',
    allHosts: 'Kaikki palvelimet',
    saveChanges: 'Tallenna muutokset',
    createMaintenance: 'Luo huolto',
    hosts: 'Palvelimet',
    maintenanceStartTime: 'Huollon alkamisaika',
    repeatStarts: 'Toisto alkaa',
    maintenance: 'Huolto',
    areYouSureWantToCancelMaintenance: 'Haluatko varmasti keskeyttää huollon?',
    areYouSureWantToDeleteMaintenance: 'Haluatko varmasti poistaa huollon?',
    cantCancelStartedPeriodicMaintenance: 'Käynnissä olevaa ajastettua huoltoa ei voi keskeyttää.',
    selectedActionWillDeleteAllMaintenancesInSeries:
      'Valitsemasi toiminto poistaa kaikki samaan sarjaan kuuluvat huollot.',
    areYouSureWantToContinue: 'Haluatko varmasti jatkaa?',
    areYouSureWantToDeletePeriodicMaintenance: 'Haluatko varmasti poistaa ajastetun huollon?',
    allMaintenancesInSeriesWillBeDeleted: 'Kaikki samaan sarjaan kuuluvat tulevat huollot poistetaan.',
    maintenanceHasBeenDeleted: 'Huolto on poistettu onnistuneesti.',
    maintenancehasBeenCanceled: 'Huolto on keskeytetty.',
    systemStatusWillBeUpdated: 'Järjestelmän tila päivittyy 1-2 minuutissa.',
    newMaintenanceHasBeenStarted: 'Uusi huolto on käynnistetty onnistuneesti.',
    maintenanceHasBeenUpdated: 'Huolto on päivitetty onnistuneesti.',
    newMaintenanceHasBeenCreated: 'Uusi huolto luotu onnistuneesti.',
  },
  en: {
    upcomingMaintenances: 'Upcoming Maintenances',
    type: 'Type',
    description: 'Description',
    createdBy: 'Created by',
    startTime: 'Start time',
    endTime: 'End time',
    duration: 'Duration',
    repeatEnds: 'Repeat ends',
    createNewMaintenance: 'Create new maintenance',
    ok: 'OK',
    cancel: 'Cancel',
    oneTime: 'One time',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    oneTimeAbbr: 'one',
    dailyAbbr: 'dly',
    weeklyAbbr: 'wkly',
    monthlyAbbr: 'mthly',
    first: 'First',
    second: 'Second',
    third: 'Third',
    fourth: 'Fourth',
    last: 'Last',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    january: 'January',
    february: 'February',
    march: 'March',
    april: 'April',
    may: 'May',
    june: 'June',
    july: 'July',
    august: 'August',
    september: 'September',
    october: 'October',
    november: 'November',
    december: 'December',
    atLeastOneHostMustBeSelected: 'At least one host must be selected',
    maintenanceDescriptionIs: 'Maintenance description is',
    charsTooLong: 'characters too long',
    dayFieldMustContainInteger: 'Field "Repeat every n days" must contain an integer.',
    weekFieldMustContainInteger: 'Field "Repeat every n weeks" must contain an integer.',
    oneWeekdayMustBeChosen: 'At least one weekday must be chosen.',
    oneMonthMustBeChosen: 'At least one month must be chosen.',
    monthFieldMustContainInteger: 'Field "Repeat day of month" must contain an integer.',
    repeatMustEndAfterStartTime: 'Repeat must after maintenance start time.',
    repeatEndTimeCantBeInPast: "Repeat end time can't be in the past.",
    repeatEndTimeCantOverlapDaylight: "Repeat end time can't overlap daylight save time.",
    maintenanceEndMustBeAfterStart: 'Maintenance end time must be after start time.',
    maintenanceEndCantBeInPast: "Maintenance end time can't be in the past.",
    maintenanceType: 'Maintenance type',
    repeatEveryNDays: 'Repeat every [n] days',
    repeatEveryNWeeks: 'Repeat every [n] weeks',
    repeatOnWeekday: 'Repeat on weekday',
    repeatOnMonth: 'Repeat on month',
    selectAll: 'Select all',
    repeatOn: 'Repeat on',
    nthDayOfMonth: 'Nth day of month',
    nthDayOfWeek: 'Nth day of week',
    repeatOnDayOfMonth: 'Repeat on day of month',
    repeatOnDayOfWeek: 'Repeat on day of week',
    secondTuesdayOfApril: '(e.g. 2nd Tuesday of April)',
    day: 'Day',
    month: 'Month',
    year: 'Year',
    hour: 'Hour',
    minute: 'Minute',
    endRepeat: 'End repeat',
    maintenanceDuration: 'Maintenance duration',
    setPreciseEndTime: 'Set precise end time',
    maintenanceEndTime: 'Maintenance end time',
    back: 'Back',
    next: 'Next',
    maintenanceDescription: 'Maintenance description',
    selectHosts: 'Select hosts',
    allHosts: 'All hosts',
    saveChanges: 'Save changes',
    createMaintenance: 'Create maintenance',
    hosts: 'Hosts',
    maintenanceStartTime: 'Maintenance start time',
    repeatStarts: 'Repeat starts',
    maintenance: 'Maintenance',
    areYouSureWantToCancelMaintenance: 'Are you sure you want to cancel maintenance?',
    areYouSureWantToDeleteMaintenance: 'Are you sure you want to delete maintenance?',
    cantCancelStartedPeriodicMaintenance: "You can't cancel a periodic maintenance which has been started.",
    selectedActionWillDeleteAllMaintenancesInSeries:
      'The selected action will delete all maintenances in the same series.',
    areYouSureWantToContinue: 'Are you sure you want to continue?',
    areYouSureWantToDeletePeriodicMaintenance: 'Are you sure you want to delete a periodic maintenance?',
    allMaintenancesInSeriesWillBeDeleted: 'All maintenances in the same series will be deleted.',
    maintenanceHasBeenDeleted: 'Maintenance has been succesfully deleted.',
    maintenancehasBeenCanceled: 'Maintenance has been canceled.',
    systemStatusWillBeUpdated: 'The system status will be updated in 1-2 minutes.',
    newMaintenanceHasBeenStarted: 'New maintenance has been started succesfully.',
    maintenanceHasBeenUpdated: 'Maintenance has been updated succesfully.',
    newMaintenanceHasBeenCreated: 'New maintenance has been created succesfully.',
  },
};
