export const localizations: any = {
  fi: {
    upcomingMaintenances: 'Tulevat huollot',
    type: 'Tyyppi',
    description: 'Kuvaus',
    createdBy: 'Luonut',
    startTime: 'Alkamisaika',
    endTime: 'Päättymisaika',
    duration: 'Kesto',
    repeatEnds: 'Toisto päättyy',
    createNewMaintenance: 'Luo uusi huolto',
    ok: 'OK',
    cancel: 'Peruuta',
    oneTime: 'Yksittäinen',
    daily: 'Päivittäinen',
    weekly: 'Viikottainen',
    monthly: 'Kuukausittainen',
    oneTimeAbbr: 'yksi',
    dailyAbbr: 'pvä',
    weeklyAbbr: 'vko',
    monthlyAbbr: 'kk',
    first: 'Ensimmäinen',
    second: 'Toinen',
    third: 'Kolmas',
    fourth: 'Neljäs',
    last: 'Viimeinen',
    monday: 'Maanantai',
    tuesday: 'Tiistai',
    wednesday: 'Keskiviikko',
    thursday: 'Torstai',
    friday: 'Perjantai',
    saturday: 'Lauantai',
    sunday: 'Sunnuntai',
    january: 'Tammikuu',
    february: 'Helmikuu',
    march: 'Maaliskuu',
    april: 'Huhtikuu',
    may: 'Toukokuu',
    june: 'Kesäkuu',
    july: 'Heinäkuu',
    august: 'Elokuu',
    september: 'Syyskuu',
    october: 'Lokakuu',
    november: 'Marraskuu',
    december: 'Joulukuu',
    atLeastOneHostMustBeSelected: 'Ainakin yhden palvelimen täytyy olla valittu',
    maintenanceDescriptionIs: 'Huollon kuvaus on',
    charsTooLong: 'merkkiä liian pitkä',
    dayFieldMustContainInteger: 'Kentän "Toistetaan n päivän välein" täytyy sisältää kokonaisluku.',
    weekFieldMustContainInteger: 'Kentän "Toistetaan n viikon välein" täytyy sisältää kokonaisluku.',
    oneWeekdayMustBeChosen: 'Ainakin yhden viikonpäivän täytyy olla valittu.',
    oneMonthMustBeChosen: 'Ainakin yhden kuukauden täytyy olla valittu.',
    monthFieldMustContainInteger: 'Kentän "Toistetaan kuukauden päivänä" täytyy sisältää kokonaisluku.',
    repeatMustEndAfterStartTime: 'Toiston päättymisaika pitää olla huollon alkamisajan jälkeen.',
    repeatEndTimeCantBeInPast: 'Toiston päättymisaika ei voi olla menneisyydessä.',
    repeatEndTimeCantOverlapDaylight: 'Toiston päättymisaika ei voi ylittää kesä/talviaika vaihdosta.',
    maintenanceEndMustBeAfterStart: 'Huollon päättymisajan pitää olla huollon alkamisajan jälkeen.',
    maintenanceEndCantBeInPast: 'Huollon päättymisaika ei voi olla menneisyydessä.',
  },
  en: {
    upcomingMaintenances: 'Upcoming Maintenances',
    type: 'Type',
    description: 'Description',
    createdBy: 'Created by',
    startTime: 'Start time',
    endTime: 'End time',
    duration: 'Duration',
    repeatEnds: 'Repeat ends',
    createNewMaintenance: 'Create new maintenance',
    ok: 'OK',
    cancel: 'Cancel',
    oneTime: 'One time',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    oneTimeAbbr: 'one',
    dailyAbbr: 'dly',
    weeklyAbbr: 'wkly',
    monthlyAbbr: 'mthly',
    first: 'First',
    second: 'Second',
    third: 'Third',
    fourth: 'Fourth',
    last: 'Last',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    january: 'January',
    february: 'February',
    march: 'March',
    april: 'April',
    may: 'May',
    june: 'June',
    july: 'July',
    august: 'August',
    september: 'September',
    october: 'October',
    november: 'November',
    december: 'December',
    atLeastOneHostMustBeSelected: 'At least one host must be selected',
    maintenanceDescriptionIs: 'Maintenance description is',
    charsTooLong: 'characters too long',
    dayFieldMustContainInteger: 'Field "Repeat every n days" must contain an integer.',
    weekFieldMustContainInteger: 'Field "Repeat every n weeks" must contain an integer.',
    oneWeekdayMustBeChosen: 'At least one weekday must be chosen.',
    oneMonthMustBeChosen: 'At least one month must be chosen.',
    monthFieldMustContainInteger: 'Field "Repeat day of month" must contain an integer.',
    repeatMustEndAfterStartTime: 'Repeat must after maintenance start time.',
    repeatEndTimeCantBeInPast: "Repeat end time can't be in the past.",
    repeatEndTimeCantOverlapDaylight: "Repeat end time can't overlap daylight save time.",
    maintenanceEndMustBeAfterStart: 'Maintenance end time must be after start time.',
    maintenanceEndCantBeInPast: "Maintenance end time can't be in the past.",
  },
};
